### ISSUE TITLE
Quick POC on Image download of Viz along with associated metadata

### ISSUE THREAD

**Issue by navsie** [cbgaindia/story-generator#42]

**Comment by tejasrivastav** [comment]
Since we don't have a server-side implementation.
We need a to convert the rendered DOM to image and trigger download.
Approach:
- convert the dom to canvas
- trigger image download on canvas 

Plugins with similar approach
- https://github.com/niklasvh/html2canvas
- https://github.com/pbakaus/domvas

Nothing concrete as of now since the plugins are still in budding stage
